### ISSUE TITLE
cannot estimate tree

### ISSUE THREAD

**Issue by BaiweiLo** [acg-team/bpp-arpip#1]
Hi,

I ran into an error while trying to let arpip estimate tree.

It happened both on the testing data and my own data.
The command I use was:
ARPIP params=../data/input/test_03/conf.txt

and the error message I get is:

[                                      ]   0%ARPIP exception:
AlphabetException: BadIntException: -1. AbstractSubstitutionModel::getInitValue. Character - is not allowed in model.
F20230102 17:38:46.892885 30902 main.cpp:735] Error: AlphabetException: BadIntException: -1. AbstractSubstitutionModel::getInitValue. Character - is not allowed in model.
*** Check failure stack trace: ***
    @     0x7f45094ef67c  google::LogMessage::Fail()
    @     0x7f45094ef5db  google::LogMessage::SendToLog()
    @     0x7f45094eeef4  google::LogMessage::Flush()
    @     0x7f45094f2448  google::LogMessageFatal::~LogMessageFatal()
    @           0x42c3b5  main.cold
    @     0x7f4508ff220a  __libc_start_call_main
    @     0x7f4508ff22bc  __libc_start_main_alias_2
    @           0x432b7a  _start
Aborted (core dumped)

Also I am wondering is there is a manual where I can see all the parameters for ARPIP?

Thanks for helping.

**Comment by GhJowkar** [comment]
Dear Steve,

Please accept my apology for the late reply, as I just noticed you'd opened an issue.

The problem was due to adding new features to the code, which contributed to inconsistency within the code. It's now resolved, and all the test files are working fine. Please let me know if you still have a problem.

Regarding your question, we only have two parameters (death and birth rates) for the PIP model. We have short documentation attached to the source code ([here](https://acg-team.github.io/bpp-arpip/index.html)). Feel free to write me an email if you have more questions.

Best regards,
Gholam-Hossein
